# Generated by Django 5.1.6 on 2025-03-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$IMLHhQJTk3z9jZUnviXLVY$gvYZztZB3Gvk+6ewf0SbRcdEi9wmao6Wc24Nbr73gLQ=', max_length=128),
        ),
    ]
