# Generated by Django 5.1.6 on 2025-03-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$MTXWUU1X7xgm8X3lIE3Nvr$tyYXX9Kf2OTXi8x6mJaAmwlYC93abuXuEWqCaRnb7AA=', max_length=128),
        ),
    ]
