# Generated by Django 5.1.6 on 2025-03-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_user_password_draft_draftservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestservice',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$vzKybhs1FObms0cQ3J6YgU$59xfOnlDK5w4LXYL8GfcKi3TvYT3k9kCY8b65jdw1Fw=', max_length=128),
        ),
    ]
