# Generated by Django 5.1.6 on 2025-03-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_requestservice_quantity_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$hT8uE0uPRmrro1MbCUbSp2$iYRYWDi4z0g1ZtspiffA59JUVz+UW8rQWtryfMvdMp0=', max_length=128),
        ),
    ]
