version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: glasses_shop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123321
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql